# Generated by Django 4.2.16 on 2026-05-17 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbTestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.abtest')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.abtestvariant')),
            ],
            options={
                'db_table': 'ab_test_assignments',
                'unique_together': {('test', 'session_id')},
            },
        ),
    ]
