# Generated by Django 4.2.30 on 2026-07-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokentransaction',
            name='type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('tip', 'Tip'), ('receive', 'Receive'), ('commission', 'Commission'), ('withdrawal', 'Withdrawal'), ('refund', 'Refund'), ('integration', 'Integration Charge')], max_length=20),
        ),
    ]
