# Generated by Django 4.2.16 on 2026-05-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_apiclient_apiendpointconfig_cdnconfig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('crypto', 'Crypto'), ('papara', 'Papara')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('public_key', models.TextField(blank=True, null=True)),
                ('secret_key', models.TextField(blank=True, null=True)),
                ('api_key', models.TextField(blank=True, null=True)),
                ('merchant_id', models.CharField(blank=True, max_length=200, null=True)),
                ('wallet_address', models.CharField(blank=True, max_length=200, null=True)),
                ('network', models.CharField(blank=True, max_length=50, null=True)),
                ('is_test_mode', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('total_volume', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tx_count', models.IntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payment_gateways',
                'ordering': ['-added_at'],
            },
        ),
    ]
