# Generated by Django 4.2.16 on 2026-06-26 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_seo_webhook_advanced'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('platform', models.CharField(choices=[('discord', 'Discord'), ('slack', 'Slack'), ('zapier', 'Zapier'), ('make', 'Make (Integromat)'), ('n8n', 'n8n'), ('ifttt', 'IFTTT'), ('pipedream', 'Pipedream'), ('teams', 'Microsoft Teams'), ('telegram', 'Telegram Bot'), ('custom', 'Custom HTTP')], default='custom', max_length=30)),
                ('url', models.TextField()),
                ('secret', models.CharField(blank=True, default='', max_length=500)),
                ('events', models.JSONField(default=list)),
                ('is_enabled', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('failing', 'Failing'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('total_deliveries', models.IntegerField(default=0)),
                ('success_deliveries', models.IntegerField(default=0)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('last_status_code', models.IntegerField(blank=True, null=True)),
                ('max_retries', models.IntegerField(default=3)),
                ('timeout_secs', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'webhook_endpoints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('request_body', models.TextField(blank=True)),
                ('request_headers', models.JSONField(default=dict)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('attempt', models.IntegerField(default=1)),
                ('max_attempts', models.IntegerField(default=3)),
                ('error', models.TextField(blank=True)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='admin_panel.webhookendpoint')),
            ],
            options={
                'db_table': 'webhook_deliveries',
                'ordering': ['-triggered_at'],
                'indexes': [models.Index(fields=['endpoint', '-triggered_at'], name='webhook_del_endpoin_1c6ebb_idx'), models.Index(fields=['event', '-triggered_at'], name='webhook_del_event_94170a_idx'), models.Index(fields=['status'], name='webhook_del_status_269a2c_idx')],
            },
        ),
    ]
