# Generated by Django 4.2.16 on 2026-06-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crosspost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crosspostsite',
            name='accepts_adult',
            field=models.BooleanField(default=False, help_text='+18 içerik kabul eder mi?'),
        ),
        migrations.AddField(
            model_name='crosspostsite',
            name='provider_color',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='crosspostsite',
            name='provider_key',
            field=models.CharField(blank=True, default='', help_text='Katalog sağlayıcı anahtarı (örn: pornhub, youtube)', max_length=64),
        ),
        migrations.AddField(
            model_name='crosspostsite',
            name='provider_letter',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
    ]
