# Generated by Django 5.2.15 on 2026-06-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='deviceinteraction',
            new_name='device_inte_device__bef120_idx',
            old_name='dev_int_dev_created_idx',
        ),
        migrations.RenameIndex(
            model_name='deviceinteraction',
            new_name='device_inte_video_i_56ff5a_idx',
            old_name='dev_int_video_idx',
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deviceinteraction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
