# Generated by Django 4.2.16 on 2026-05-18 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossPostSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('base_url', models.CharField(blank=True, default='', max_length=500)),
                ('upload_endpoint', models.CharField(blank=True, default='', help_text='Full URL the video payload is POSTed to.', max_length=500)),
                ('login_endpoint', models.CharField(blank=True, default='', max_length=500)),
                ('adapter', models.CharField(choices=[('generic_webhook', 'Generic Webhook (POST JSON)'), ('multipart_form', 'Multipart Form Upload'), ('manual', 'Manual / No automation')], default='generic_webhook', max_length=32)),
                ('username', models.CharField(blank=True, default='', max_length=200)),
                ('password', models.CharField(blank=True, default='', max_length=500)),
                ('api_key', models.CharField(blank=True, default='', max_length=500)),
                ('extra_headers', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('auto_post', models.BooleanField(default=True, help_text='Cross-post otomatik tetiklensin mi?')),
                ('last_login_ok', models.BooleanField(default=False)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crosspost_sites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CrossPostJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('success', 'success'), ('failed', 'failed'), ('skipped', 'skipped')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('response_text', models.TextField(blank=True, default='')),
                ('remote_url', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='crosspost.crosspostsite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crosspost_jobs', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crosspost_jobs', to='videos.video')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
