# Generated by Django 5.2.15 on 2026-06-28 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_video_categories_m2m'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoHeatmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segments', models.JSONField(default=list)),
                ('total_sessions', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='heatmap', to='videos.video')),
            ],
            options={
                'db_table': 'video_heatmaps',
            },
        ),
    ]
