# Generated by Django 4.2.16 on 2026-05-17 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorUploadLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_file_size_mb', models.IntegerField(default=2048)),
                ('max_duration_sec', models.IntegerField(default=3600)),
                ('max_daily_uploads', models.IntegerField(default=5)),
                ('max_resolution', models.CharField(default='4K', max_length=20)),
                ('allowed_types', models.JSONField(default=list)),
                ('premium_allowed', models.BooleanField(default=True)),
                ('ppv_allowed', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upload_limit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'creator_upload_limits',
            },
        ),
    ]
