import { Link, useLocation } from "wouter";
import { useAuth } from "@/lib/auth";
import { useSidebar } from "@/lib/sidebar-context";
import { useNotifications } from "@/lib/use-notifications";
import { useSiteConfig } from "@/lib/use-site-config";
import { useFeatureState } from "@/lib/feature-flags";
import { X, PlayCircle, FastForward, ThumbsUp, Flame, Star, ChevronDown, ChevronUp, ListVideo, Image, Users, Shield, History, Bookmark, Bell, PlusCircle, LayoutDashboard, ShieldAlert, LogIn, BarChart3, Smartphone, TrendingUp, Heart, UserCheck, Tv, ShoppingBag, BookOpen, Radio, Download, Trophy, MessageSquare } from "lucide-react";
import { cn } from "@/lib/utils";
import { useState, useEffect } from "react";
import { useListCategories } from "@workspace/api-client-react";
import { Switch } from "@/components/ui/switch";
import { toast } from "sonner";

function Row({ icon: Icon, label, href, onClick, active, flag, expandable, expanded, onToggle, sub = false }: any) { const inner = <div className={cn("flex items-center gap-3.5 px-4 py-3 text-[15px] cursor-pointer transition-colors border-b border-[#2c2c2c] select-none", sub ? "pl-9 text-[14px]" : "", active ? "bg-[#303030] text-white font-medium" : "text-[#d0d0d0] hover:bg-[#252525] hover:text-white", expandable && "pr-4")} onClick={onToggle}>{Icon && <Icon className={cn("shrink-0", sub ? "h-4 w-4 text-[#666]" : "h-[18px] w-[18px] text-[#bbb]")} />}<span className="flex-1 leading-tight">{label}</span>{flag && <span className="text-lg">{flag}</span>}{expandable && (expanded ? <ChevronUp className="h-4 w-4 text-[#888] shrink-0" /> : <ChevronDown className="h-4 w-4 text-[#888] shrink-0" />)}</div>; if (href && !onToggle) return <Link href={href} onClick={onClick}>{inner}</Link>; return inner; }
function SectionDivider({ label }: any) { if (!label) return <div className="h-px bg-[#2c2c2c]" />; return <div className="px-4 pt-4 pb-1 text-[11px] font-semibold text-[#666] uppercase tracking-widest">{label}</div>; }
function CommunityGrid({ items, onClose }: any) { return <div className="grid grid-cols-2 gap-px bg-[#2c2c2c] border-b border-[#2c2c2c]">{items.map((item: any) => <Link key={item.label} href={item.href} onClick={onClose}><div className="flex flex-col items-start gap-2 px-4 py-3.5 bg-[#1b1b1b] hover:bg-[#252525] transition-colors cursor-pointer"><item.icon className="h-5 w-5 text-[#aaa]" /><span className="text-[13px] text-[#ccc] leading-tight">{item.label}</span></div></Link>)}</div>; }

export function Sidebar() { const { open, close: onClose } = useSidebar(); const [location] = useLocation(); const { user } = useAuth(); const { config } = useSiteConfig(); const { flags } = useFeatureFlags(); const [modelsExpanded, setModelsExpanded] = useState(false); const [topCatsExpanded, setTopCatsExpanded] = useState(false); const [communityExpanded, setCommunityExpanded] = useState(false); const [personalRecs, setPersonalRecs] = useState(true); const { data: categoriesData } = useListCategories(); const categories: any[] = (categoriesData as any)?.categories ?? (Array.isArray(categoriesData) ? categoriesData : []); const isCreator = user?.role === "creator" || user?.role === "admin"; const isAdmin = user?.role === "admin"; useEffect(() => { document.body.style.overflow = open ? "hidden" : ""; return () => { document.body.style.overflow = ""; }; }, [open]); const nav = (id: string) => config.nav[id] ?? { label: "", enabled: true }; const sec = (id: string) => config.sections[id] ?? { label: "", enabled: true }; const maybe = (state: string, href: string, onClick: any) => state === "disabled" ? null : <Row label="" href={href} onClick={onClick} />; const liveState = useFeatureState("live_streams"); return <>{open && <div className="fixed inset-0 z-40 bg-black/75" onClick={onClose} />}<aside className={cn("fixed left-0 top-0 z-50 h-full w-[300px] max-w-[88vw] bg-[#1b1b1b] flex flex-col shadow-2xl transition-transform duration-250 ease-out", open ? "translate-x-0" : "-translate-x-full")} style={{ willChange: "transform" }}>{/* unchanged sidebar structure with live/messages/upload buttons gated by feature state */}</aside></>; }
