# Generated by Django 4.2.30 on 2026-07-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_abtestassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=200)),
                ('country', models.CharField(default='', max_length=10)),
                ('city', models.CharField(default='', max_length=100)),
                ('lat', models.FloatField(default=0.0)),
                ('lng', models.FloatField(default=0.0)),
                ('page', models.CharField(default='/', max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'visitor_logs',
                'indexes': [models.Index(fields=['timestamp', 'country'], name='visitor_log_timesta_72377a_idx')],
            },
        ),
    ]
