# Generated by Django 4.2.30 on 2026-07-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_visitor_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorReportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('recipients', models.JSONField(default=list)),
                ('frequency', models.CharField(choices=[('daily', 'Günlük'), ('weekly', 'Haftalık'), ('monthly', 'Aylık')], default='weekly', max_length=20)),
                ('day_of_week', models.IntegerField(default=0, help_text='0=Pzt … 6=Paz (haftalık için)')),
                ('hour', models.IntegerField(default=8, help_text='0-23 arası saat')),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'visitor_report_settings',
            },
        ),
    ]
