# Generated by Django 5.2.15 on 2026-06-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='trainingevent',
            new_name='ai_training_status_38cabe_idx',
            old_name='ai_te_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='trainingevent',
            new_name='ai_training_event_t_b4e0e7_idx',
            old_name='ai_te_event_type_idx',
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='categoryprediction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trainingevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
