# Generated by Django 4.2.16 on 2026-06-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_seo_webhook_extended'),
    ]

    operations = [
        migrations.AddField(
            model_name='seosettings',
            name='canonical_url',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='google_analytics_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='google_search_console',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='hreflang',
            field=models.CharField(default='tr', max_length=10),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='og_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='og_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='og_type',
            field=models.CharField(default='website', max_length=30),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='schema_org_type',
            field=models.CharField(default='Organization', max_length=50),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='sitemap_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='structured_data_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='twitter_card',
            field=models.CharField(default='summary_large_image', max_length=30),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='twitter_creator',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='twitter_site',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='webhooksettings',
            name='endpoints',
            field=models.JSONField(default=list),
        ),
    ]
