# Generated by Django 5.2.15 on 2026-06-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_homefilter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homefilter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
