# Generated by Django 4.2.16 on 2026-06-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_add_video_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosubtitle',
            name='moderation_status',
            field=models.CharField(choices=[('approved', 'Onaylandı'), ('pending', 'Beklemede'), ('rejected', 'Reddedildi')], default='approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='videosubtitle',
            name='language',
            field=models.CharField(max_length=50),
        ),
    ]
