# Generated by Django 4.2.17 on 2026-07-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_add_like_premium_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['home_order', 'name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='home_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='show_on_home',
            field=models.BooleanField(default=True),
        ),
    ]
