# Generated by Django 4.2.30 on 2026-07-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0012_alter_category_options_category_home_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='guest_like_count',
            field=models.IntegerField(default=0),
        ),
    ]
