# Generated by Django 4.2.16 on 2026-05-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Soci', max_length=200)),
                ('site_description', models.TextField(default='')),
                ('logo_url', models.TextField(blank=True, null=True)),
                ('favicon_url', models.TextField(blank=True, null=True)),
                ('primary_color', models.CharField(default='#7c3aed', max_length=20)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('registration_enabled', models.BooleanField(default=True)),
                ('creator_application_enabled', models.BooleanField(default=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'site_settings',
            },
        ),
    ]
