# Generated by Django 4.2.16 on 2026-05-17 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('client_key', models.CharField(max_length=100, unique=True)),
                ('client_secret', models.CharField(max_length=200)),
                ('developer_domain', models.CharField(default='developer.sitelinli', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'api_clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiEndpointConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(default='')),
                ('url', models.TextField()),
                ('method', models.CharField(default='GET', max_length=10)),
                ('headers', models.TextField(default='{}')),
                ('body', models.TextField(default='')),
                ('category', models.CharField(default='Genel', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'api_endpoint_configs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CdnConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('endpoint', models.TextField(blank=True, null=True)),
                ('access_key', models.TextField(blank=True, null=True)),
                ('secret_key', models.TextField(blank=True, null=True)),
                ('bucket', models.CharField(blank=True, max_length=200, null=True)),
                ('region', models.CharField(default='auto', max_length=50)),
                ('cdn_url', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cdn_configs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('login', models.CharField(blank=True, max_length=200, null=True)),
                ('key', models.TextField(blank=True, null=True)),
                ('api_key', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('auto_upload', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('upload_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'integration_configs',
                'ordering': ['-created_at'],
            },
        ),
    ]
