# Generated by Django 4.2.16 on 2026-06-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_moderation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='scheduled_publish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
