# Generated by Django 5.2.15 on 2026-06-27 20:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_scheduled_publish'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['is_published', '-created_at'], name='video_pub_date_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['is_published', '-view_count'], name='video_pub_views_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['is_published', 'type', '-created_at'], name='video_pub_type_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['creator', 'is_published'], name='video_creator_pub_idx'),
        ),
    ]
