# Generated by Django 5.2.15 on 2026-06-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_add_hls_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='videos_m2m', to='videos.category'),
        ),
    ]
