# Generated by Django 5.2.15 on 2026-06-30 22:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_video_heatmap'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['is_published', '-like_count'], name='video_pub_likes_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['is_published', 'is_premium', '-view_count'], name='video_pub_prem_idx'),
        ),
    ]
