# Generated by Django 4.2.16 on 2026-05-17 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sms_otp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
