# Generated by Django 4.2.17 on 2026-07-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_integration_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='service_worker_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
