# Generated by Django 4.2.17 on 2026-07-13 17:50

from django.db import migrations, models


def _turn_off_existing(apps, schema_editor):
    SiteSettings = apps.get_model('admin_panel', 'SiteSettings')
    SiteSettings.objects.update(service_worker_enabled=False)


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_service_worker_toggle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='service_worker_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(_turn_off_existing, migrations.RunPython.noop),
    ]
