# Generated by Django 4.2.16 on 2026-05-17 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ab_tests',
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled'), ('maintenance', 'Maintenance')], default='enabled', max_length=20)),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'feature_flags',
            },
        ),
        migrations.CreateModel(
            name='GeoRestrictionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('mode', models.CharField(choices=[('allowlist', 'Allowlist'), ('blocklist', 'Blocklist')], default='blocklist', max_length=20)),
                ('countries', models.JSONField(default=list)),
                ('redirect_url', models.TextField(blank=True, null=True)),
                ('message', models.TextField(default='Bu içerik bulunduğunuz ülkede kullanılamaz.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'geo_restriction_settings',
            },
        ),
        migrations.CreateModel(
            name='ApiEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=300)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_auth', models.BooleanField(default=True)),
                ('rate_limit', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'api_endpoints',
                'unique_together': {('path', 'method')},
            },
        ),
        migrations.CreateModel(
            name='AbTestVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('weight', models.IntegerField(default=50)),
                ('view_count', models.IntegerField(default=0)),
                ('conversion_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='core.abtest')),
            ],
            options={
                'db_table': 'ab_test_variants',
            },
        ),
    ]
