# Generated by Django 5.2.15 on 2026-06-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crosspost', '0002_add_provider_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crosspostsite',
            name='adapter',
            field=models.CharField(choices=[('streamtape', 'StreamTape API'), ('doodstream', 'DoodStream API'), ('mixdrop', 'Mixdrop API'), ('vidoza', 'Vidoza API'), ('filemoon', 'FileMoon API'), ('streamwish', 'StreamWish API'), ('voe', 'Voe.sx API'), ('upstream', 'Upstream API'), ('vidhide', 'VidHide API'), ('luluvdo', 'Luluvdo API'), ('uqload', 'Uqload API'), ('streamhide', 'StreamHide API'), ('supervideo', 'SuperVideo API'), ('dropload', 'Dropload API'), ('embedsito', 'Embedsito API'), ('vidlox', 'Vidlox API'), ('streamlare', 'Streamlare API'), ('clipwatching', 'ClipWatching API'), ('streamsb', 'StreamSB API'), ('hxfile', 'HXFile API'), ('vidplay', 'VidPlay API'), ('nxbex', 'Nxbex API'), ('dropgalaxy', 'DropGalaxy API'), ('evoload', 'Evoload API'), ('fembed', 'Fembed API'), ('hotlinking', 'Hotlinking API'), ('filelions', 'FileLions API'), ('vidmoly', 'VidMoly API'), ('streamhub', 'StreamHub API'), ('videovard', 'VideoVard API'), ('waaw', 'Waaw.tv API'), ('upvid', 'UpVid API'), ('vtube', 'VTube API'), ('abysscdn', 'AbyssCDN API'), ('filebee', 'FileBee API'), ('vipfile', 'VipFile API'), ('vidmam', 'VidMam API'), ('moonvid', 'MoonVid API'), ('gobig', 'GoBig API'), ('jetload', 'JetLoad API'), ('sendvid', 'SendVid API'), ('rapidvideo', 'RapidVideo API'), ('vidcrypt', 'VidCrypt API'), ('embedrise', 'EmbedRise API'), ('kvid', 'KVid API'), ('megaup', 'MegaUp API'), ('generic_webhook', 'Generic Webhook (POST JSON)'), ('multipart_form', 'Multipart Form Upload'), ('manual', 'Manuel (otomatik yok)')], default='generic_webhook', max_length=32),
        ),
        migrations.AlterField(
            model_name='crosspostsite',
            name='provider_key',
            field=models.CharField(blank=True, default='', help_text='Katalog sağlayıcı anahtarı (örn: streamtape, youtube)', max_length=64),
        ),
    ]
